name: background_location_demo
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  background_location: ^0.13.0
  riverpod: ^2.6.1
  flutter_riverpod: ^2.6.1
  permission_handler: ^11.3.1
  flutter_hooks: ^0.20.5
  hooks_riverpod: ^2.6.1
  geolocator: ^13.0.2
  open_app_settings: ^2.0.1
  shared_preferences: ^2.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
